openapi: 3.1.0
info:
  version: '6'
  x-publicVersion: true
  title: Adyen Account acceptDispute retrieve3ds2Result API
  description: "This API is used for the classic integration. If you are just starting your implementation, refer to our [new integration guide](https://docs.adyen.com/marketplaces-and-platforms) instead.\n\nThe Account API provides endpoints for managing account-related entities on your platform. These related entities include account holders, accounts, bank accounts, shareholders, and verification-related documents. The management operations include actions such as creation, retrieval, updating, and deletion of them.\n\nFor more information, refer to our [documentation](https://docs.adyen.com/marketplaces-and-platforms/classic).\n## Authentication\nYour Adyen contact will provide your API credential and an API key. To connect to the API, add an `X-API-Key` header with the API key as the value, for example:\n\n ```\ncurl\n-H \"Content-Type: application/json\" \\\n-H \"X-API-Key: YOUR_API_KEY\" \\\n...\n```\n\nAlternatively, you can use the username and password to connect to the API using basic authentication. For example:\n\n```\ncurl\n-U \"ws@MarketPlace.YOUR_PLATFORM_ACCOUNT\":\"YOUR_WS_PASSWORD\" \\\n-H \"Content-Type: application/json\" \\\n...\n```\nWhen going live, you need to generate new web service user credentials to access the [live endpoints](https://docs.adyen.com/development-resources/live-endpoints).\n\n## Versioning\nThe Account API supports [versioning](https://docs.adyen.com/development-resources/versioning) using a version suffix in the endpoint URL. This suffix has the following format: \"vXX\", where XX is the version number.\n\nFor example:\n```\nhttps://cal-test.adyen.com/cal/services/Account/v6/createAccountHolder\n```"
  x-timestamp: '2023-05-30T15:27:20Z'
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
servers:
- url: https://cal-test.adyen.com/cal/services/Account/v6
tags:
- name: retrieve3ds2Result
paths:
  /retrieve3ds2Result:
    post:
      tags:
      - retrieve3ds2Result
      summary: Adyen Get the 3DS2 Authentication Result
      description: Retrieves the `threeDS2Result` after doing a 3D Secure 2 authentication only.
      x-addedInVersion: '40'
      operationId: post-retrieve3ds2Result
      x-sortIndex: 4
      x-methodName: retrieve3ds2Result
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            examples:
              retrieve3ds2Result:
                $ref: '#/components/examples/post-retrieve3ds2Result-retrieve3ds2Result'
            schema:
              $ref: '#/components/schemas/ThreeDS2ResultRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreeDS2ResultResponse'
              examples:
                post-retrieve3ds2Result200Example:
                  summary: Default post-retrieve3ds2Result 200 response
                  x-microcks-default: true
                  value:
                    threeDS2Result: example_value
          description: OK - the request has succeeded.
        '400':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-400'
              schema:
                $ref: '#/components/schemas/ServiceError'
          description: Bad Request - a problem reading or understanding the request.
        '401':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-401'
              schema:
                $ref: '#/components/schemas/ServiceError'
          description: Unauthorized - authentication required.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                post-retrieve3ds2Result403Example:
                  summary: Default post-retrieve3ds2Result 403 response
                  x-microcks-default: true
                  value:
                    additionalData: {}
                    errorCode: CODE123
                    errorType: standard
                    message: example_value
                    pspReference: REF-001
                    status: 500
          description: Forbidden - insufficient permissions to process the request.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                post-retrieve3ds2Result422Example:
                  summary: Default post-retrieve3ds2Result 422 response
                  x-microcks-default: true
                  value:
                    additionalData: {}
                    errorCode: CODE123
                    errorType: standard
                    message: example_value
                    pspReference: REF-001
                    status: 500
          description: Unprocessable Entity - a request validation error.
        '500':
          content:
            application/json:
              examples:
                generic:
                  $ref: '#/components/examples/generic-500'
              schema:
                $ref: '#/components/schemas/ServiceError'
          description: Internal Server Error - the server could not process the request.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  examples:
    post-retrieve3ds2Result-retrieve3ds2Result:
      summary: Retrieve authentication details after doing a 3D Secure 2 authentication only
      value:
        merchantAccount: YOUR_MERCHANT_ACCOUNT
        pspReference: '9935272408535455'
    generic-500:
      summary: Response code 500. Internal server error.
      value:
        status: 500
        errorCode: '905'
        message: Payment details are not supported
        errorType: configuration
        pspReference: '8516091485743033'
    generic-401:
      summary: Response code 401. Unauthorized.
      value:
        status: 401
        errorCode: '000'
        message: HTTP Status Response - Unauthorized
        errorType: security
    generic-400:
      summary: Response code 400. Bad request.
      value:
        status: 400
        errorCode: '702'
        message: 'Unexpected input: ", expected: }'
        errorType: validation
  schemas:
    ServiceError:
      properties:
        additionalData:
          x-addedInVersion: '46'
          additionalProperties:
            type: string
          description: Contains additional information about the payment. Some data fields are included only if you select them first. Go to **Customer Area** > **Developers** > **Additional data**.
          type: object
        errorCode:
          description: The error code mapped to the error message.
          type: string
        errorType:
          description: The category of the error.
          type: string
        message:
          description: A short explanation of the issue.
          type: string
        pspReference:
          description: The PSP reference of the payment.
          type: string
        status:
          description: The HTTP response status.
          format: int32
          type: integer
      type: object
    ThreeDS2ResultResponse:
      properties:
        threeDS2Result:
          description: The result of the 3D Secure 2 authentication.
          $ref: '#/components/schemas/ThreeDS2Result'
      type: object
    ThreeDS2ResultRequest:
      properties:
        merchantAccount:
          description: The merchant account identifier, with which you want to process the transaction.
          type: string
        pspReference:
          description: The pspReference returned in the /authorise call.
          type: string
      required:
      - merchantAccount
      - pspReference
      type: object
    ThreeDS2Result:
      properties:
        authenticationValue:
          description: The `authenticationValue` value as defined in the 3D Secure 2 specification.
          type: string
        cavvAlgorithm:
          x-addedInVersion: '50'
          description: The algorithm used by the ACS to calculate the authentication value, only for Cartes Bancaires integrations.
          type: string
        challengeCancel:
          x-addedInVersion: '67'
          description: Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the authentication has been cancelled. For possible values, refer to [3D Secure API reference](https://docs.adyen.com/online-payments/3d-secure/api-reference#mpidata).
          enum:
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          - '07'
          type: string
        dsTransID:
          description: The `dsTransID` value as defined in the 3D Secure 2 specification.
          type: string
        eci:
          description: The `eci` value as defined in the 3D Secure 2 specification.
          type: string
        exemptionIndicator:
          x-addedInVersion: '67'
          description: 'Indicates the exemption type that was applied by the issuer to the authentication, if exemption applied.

            Allowed values:

            * `lowValue`

            * `secureCorporate`

            * `trustedBeneficiary`

            * `transactionRiskAnalysis`

            '
          enum:
          - lowValue
          - secureCorporate
          - trustedBeneficiary
          - transactionRiskAnalysis
          type: string
        messageVersion:
          x-addedInVersion: '49'
          description: The `messageVersion` value as defined in the 3D Secure 2 specification.
          type: string
        riskScore:
          x-addedInVersion: '67'
          description: Risk score calculated by Cartes Bancaires Directory Server (DS).
          type: string
        threeDSRequestorChallengeInd:
          x-addedInVersion: '68'
          description: 'Indicates whether a challenge is requested for this transaction. Possible values:

            * **01** — No preference

            * **02** — No challenge requested

            * **03** — Challenge requested (3DS Requestor preference)

            * **04** — Challenge requested (Mandate)

            * **05** — No challenge (transactional risk analysis is already performed)

            * **06** — Data Only'
          enum:
          - '01'
          - '02'
          - '03'
          - '04'
          - '05'
          - '06'
          type: string
        threeDSServerTransID:
          description: The `threeDSServerTransID` value as defined in the 3D Secure 2 specification.
          type: string
        timestamp:
          description: The `timestamp` value of the 3D Secure 2 authentication.
          type: string
        transStatus:
          description: The `transStatus` value as defined in the 3D Secure 2 specification.
          type: string
        transStatusReason:
          description: Provides information on why the `transStatus` field has the specified value. For possible values, refer to [our docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possible-transstatusreason-values).
          type: string
        whiteListStatus:
          x-addedInVersion: '49'
          description: The `whiteListStatus` value as defined in the 3D Secure 2 specification.
          type: string
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
x-groups:
- Account holders
- Accounts
- Verification
