openapi: 3.2.0
info:
  version: '30'
  x-publicVersion: true
  title: Adyen Disputes Accept Dispute API
  description: You can use the Disputes API to automate the dispute handling process so that you can respond to disputes and chargebacks as soon as they are initiated. The Disputes API lets you retrieve defense reasons, supply and delete defense documents, and accept or defend disputes.
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
servers:
- url: https://ca-test.adyen.com/ca/services/DisputeService/v30
tags:
- name: acceptDispute
paths:
  /acceptDispute:
    post:
      tags:
      - acceptDispute
      summary: Adyen Accept a Dispute
      description: Accepts a specific dispute.
      x-addedInVersion: '1'
      operationId: post-acceptDispute
      x-sortIndex: 1
      x-methodName: acceptDispute
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            examples:
              accept-dispute:
                $ref: '#/components/examples/post-acceptDispute-accept-dispute'
            schema:
              $ref: '#/components/schemas/AcceptDisputeRequest'
      responses:
        '200':
          content:
            application/json:
              examples:
                accept-dispute:
                  $ref: '#/components/examples/post-acceptDispute-accept-dispute-200'
              schema:
                $ref: '#/components/schemas/AcceptDisputeResponse'
          description: OK - the request has succeeded.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                post-acceptDispute400Example:
                  summary: Default post-acceptDispute 400 response
                  x-microcks-default: true
                  value:
                    errorCode: CODE123
                    errorType: standard
                    message: example_value
                    pspReference: REF-001
                    status: 500
          description: Bad Request - a problem reading or understanding the request.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                post-acceptDispute401Example:
                  summary: Default post-acceptDispute 401 response
                  x-microcks-default: true
                  value:
                    errorCode: CODE123
                    errorType: standard
                    message: example_value
                    pspReference: REF-001
                    status: 500
          description: Unauthorized - authentication required.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                post-acceptDispute403Example:
                  summary: Default post-acceptDispute 403 response
                  x-microcks-default: true
                  value:
                    errorCode: CODE123
                    errorType: standard
                    message: example_value
                    pspReference: REF-001
                    status: 500
          description: Forbidden - insufficient permissions to process the request.
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                post-acceptDispute422Example:
                  summary: Default post-acceptDispute 422 response
                  x-microcks-default: true
                  value:
                    errorCode: CODE123
                    errorType: standard
                    message: example_value
                    pspReference: REF-001
                    status: 500
          description: Unprocessable Entity - a request validation error.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                post-acceptDispute500Example:
                  summary: Default post-acceptDispute 500 response
                  x-microcks-default: true
                  value:
                    errorCode: CODE123
                    errorType: standard
                    message: example_value
                    pspReference: REF-001
                    status: 500
          description: Internal Server Error - the server could not process the request.
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ServiceError:
      properties:
        errorCode:
          description: The error code mapped to the error message.
          type: string
        errorType:
          description: The category of the error.
          type: string
        message:
          description: A short explanation of the issue.
          type: string
        pspReference:
          description: The PSP reference of the payment.
          type: string
        status:
          description: The HTTP response status.
          format: int32
          type: integer
      type: object
    DisputeServiceResult:
      properties:
        errorMessage:
          description: The general error message.
          type: string
        success:
          description: Indicates whether the request succeeded.
          type: boolean
      required:
      - success
      type: object
    AcceptDisputeResponse:
      properties:
        disputeServiceResult:
          description: The result of the dispute service.
          $ref: '#/components/schemas/DisputeServiceResult'
      required:
      - disputeServiceResult
      type: object
    AcceptDisputeRequest:
      properties:
        disputePspReference:
          description: The PSP reference assigned to the dispute.
          type: string
        merchantAccountCode:
          description: The merchant account identifier, for which you want to process the dispute transaction.
          type: string
      required:
      - merchantAccountCode
      - disputePspReference
      type: object
  examples:
    post-acceptDispute-accept-dispute:
      summary: Accept a dispute
      value:
        disputePspReference: DZ4DPSHB4WD2WN82
        merchantAccountCode: YOUR_MERCHANT_ACCOUNT
    post-acceptDispute-accept-dispute-200:
      summary: Dispute accepted
      value:
        disputeServiceResult:
          success: true
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
    BasicAuth:
      scheme: basic
      type: http
